openapi: 3.0.0
info:
  title: Petstore API
  description: API магазина питомцев, предоставляющий возможность добавления, просмотра и редактирования информации о питомцах.
  version: 1.0.0
servers:
  - url: https://api.petstore.com/v1
    description: Производственная среда
  - url: https://test.api.petstore.com/v1
    description: Тестовая среда
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: API ключ для аутентификации запросов. Ключ должен быть получен у администратора.
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор питомца
        name:
          type: string
          description: Имя питомца
        status:
          type: string
          enum: [available, pending, sold]
          description: Статус питомца (доступен, на утверждении, продан)
      required:
        - id
        - name
    Error:
      type: object
      properties:
        code:
          type: integer
          description: Код ошибки
        message:
          type: string
          description: Сообщение, описывающее причину ошибки
paths:
  /pets:
    get:
      summary: Получить список всех питомцев
      description: Возвращает массив объектов питомцев.
      security:
        - apiKey: []
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '401':
          description: Неавторизованный доступ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавить нового питомца
      description: Создаёт новый питомец в системе.
      security:
        - apiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: Питомец успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Некорректные входные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
